// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/victor-nach/price-calculator/models"
)

// PriceService is an autogenerated mock type for the PriceService type
type PriceService struct {
	mock.Mock
}

// GetCurrentPrice provides a mock function with given fields:
func (_m *PriceService) GetCurrentPrice() (*models.CurrentPrice, error) {
	ret := _m.Called()

	var r0 *models.CurrentPrice
	if rf, ok := ret.Get(0).(func() *models.CurrentPrice); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CurrentPrice)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
